class character:
    character_data = [
        {
            "name": "Archer",
            "icon": "images/character/Archer/icon.png",
            "image_path": "images/character/Archer/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "idle": "images/character/Archer/Idle.png",
            "walk": "images/character/Archer/Run.png",
            "jump": "images/character/Archer/Jump.png",
            #"attack1": "images/character/Archer/Attack_1.png",
            "attack1": "images/character/Archer/Shot.png",
            "idleFrame": 9,
            "walkFrame": 8,
            "jumpFrame": 9,
            "attack1Frame": 14,
            #"shootFrame": 14,
            
        },
        {
            "name": "Samurai",
            "icon": "images/character/Samurai/icon.png",
            "image_path": "images/character/Samurai/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "idle": "images/character/Samurai/Idle.png",
            "walk": "images/character/Samurai/Run.png",
            "jump": "images/character/Samurai/Jump.png",
            "attack1": "images/character/Samurai/Attack_1.png",
            "idleFrame": 6,
            "walkFrame": 8,
            "jumpFrame": 9,
            "attack1Frame": 4,

        },
        {
            "name": "Commander",
            "icon": "images/character/Commander/icon.png",
            "image_path": "images/character/Commander/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "idle": "images/character/Commander/Idle.png",
            "walk": "images/character/Commander/Run.png",
            "jump": "images/character/Commander/Jump.png",
            "attack1": "images/character/Commander/Attack_1.png",
            "idleFrame": 5,
            "walkFrame": 8,
            "jumpFrame": 7,
            "attack1Frame": 4,
        },
    ]
