class character:
    character_data = [
        {
            "name": "Archer",
            "icon": "images/character/Archer/icon.png",
            "image_path": "images/character/Archer/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "Arrow": "images/character/Archer/Arrow.png",
            "Arrow_scale": 100,
            "idle": "images/character/Archer/Idle.png",
            "walk": "images/character/Archer/Run.png",
            "jump": "images/character/Archer/Jumpup1.png",
            "attack1": "images/character/Archer/Attack_1.png",
            "attack2": "images/character/Archer/Shot.png",
            "protect": "images/character/Archer/Protect.png",
            "fall": "images/character/Archer/Falling.png",
            "kneel": "images/character/Archer/Kneel.png",
            "dead": "images/character/Archer/Dead.png",
            "idleFrame": 9,
            "walkFrame": 8,
            "jumpFrame": 3,
            "attack1Frame": 5,
            "attack2Frame": 14,
            "protectFrame": 3,
            "fallFrame": 3,
            "kneelFrame": 2,
            "deadFrame": 5,
            
        },
        {
            "name": "Samurai",
            "icon": "images/character/Samurai/icon.png",
            "image_path": "images/character/Samurai/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "Arrow": "images/character/Samurai/Arrow.png",
            "Arrow_scale": 100,
            "idle": "images/character/Samurai/Idle.png",
            "walk": "images/character/Samurai/Run.png",
            "jump": "images/character/Samurai/Jumpup1.png",
            "attack1": "images/character/Samurai/Attack_2.png",
            "attack2": "images/character/Samurai/Ranged.png",
            "attack3": "images/character/Samurai/Attack_3.png",
            "protect": "images/character/Samurai/Protect.png",
            "fall": "images/character/Samurai/Falling.png",
            "kneel": "images/character/Samurai/Kneel.png",
            "dead": "images/character/Samurai/Dead.png",
            "idleFrame": 6,
            "walkFrame": 8,
            "jumpFrame": 3,
            "attack1Frame": 5,
            "attack2Frame": 4,
            "attack3Frame": 4,
            "protectFrame": 2,
            "fallFrame": 2,
            "kneelFrame": 2,
            "deadFrame": 6,

        },
        {
            "name": "Commander",
            "icon": "images/character/Commander/icon.png",
            "image_path": "images/character/Commander/Idle.png",
            "attack_damage": 5,
            "attack_damage_powerful": 30,
            "energy_gain_per_move": 0.5,
            "velocity": 5,
            "attack_range": 100,
            "defend_strength": 20,
            "range_damage": 5,
            "range_cooldown": 0.5,
            "Arrow": "images/character/Commander/Arrow.png",
            "Arrow_scale": 100,
            "idle": "images/character/Commander/Idle.png",
            "walk": "images/character/Commander/Run.png",
            "jump": "images/character/Commander/Jumpup1.png",
            "attack1": "images/character/Commander/Attack_2.png",
            "attack2": "images/character/Commander/Ranged2.png",
            "protect": "images/character/Commander/Protect.png",
            "fall": "images/character/Commander/Falling.png",
            "kneel": "images/character/Commander/Kneel.png",
            "dead": "images/character/Commander/Dead.png",
            "idleFrame": 5,
            "walkFrame": 8,
            "jumpFrame": 3,
            "attack1Frame": 5,
            "attack2Frame": 4,
            "protectFrame": 2,
            "fallFrame": 2,
            "kneelFrame": 2,
            "deadFrame": 6,
        },
    ]
